spring:
  application:
    name: psp-simulator
  datasource:
    url: jdbc:postgresql://localhost:${PSP_DB_PORT:5433}/psp
    username: pixlab
    password: pixlab
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

server:
  port: ${PSP_PORT:8081}

management:
  endpoints:
    web:
      exposure:
        include: health,info
