spring:
  application:
    name: psp-simulator
  datasource:
    url: jdbc:postgresql://localhost:${PSP_DB_PORT:5434}/psp
    username: pixlab
    password: pixlab
  threads:
    virtual:
      enabled: true
  mvc:
    problemdetails:
      enabled: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

server:
  port: ${PSP_PORT:8091}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: w3c
  otlp:
    metrics:
      export:
        enabled: false
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: ${OTEL_EXPORTER_OTLP_TRACES_ENDPOINT:http://localhost:4318/v1/traces}
  metrics:
    tags:
      application: ${spring.application.name}

pixlab:
  psp:
    ispb: "12345678"
    banco: "999"
  webhook:
    secret: ${PIXLAB_WEBHOOK_SECRET:pixlab-dev-secret}
  chaos:
    profiles-dir: chaos-profiles
