spring:
  application:
    name: merchant-core
  datasource:
    url: jdbc:postgresql://localhost:${MERCHANT_DB_PORT:5435}/merchant
    username: pixlab
    password: pixlab
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

server:
  port: ${MERCHANT_PORT:8090}

management:
  endpoints:
    web:
      exposure:
        include: health,info
